# Generated by Django 4.1.5 on 2023-01-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_carreras_delete_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carreras',
            old_name='cantSemestres',
            new_name='semestres',
        ),
    ]
